version: '3'

networks:
    django-docker-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.50.0/24

services:
    django-docker-nplus-sample-develop-mariadb:
    # django-docker-nplus-sample-develop-mysql:
        image: mariadb:10.5
        # image: mysql:8.0
        container_name: django-docker-nplus-sample-develop-mariadb
        # container_name: django-docker-nplus-sample-develop-mysql
        hostname: django-docker-nplus-sample-develop-mariadb
        # hostname: django-docker-nplus-sample-develop-mysql
        environment:
            MYSQL_ROOT_PASSWORD: Sz7k8Z!b
            MYSQL_DATABASE: sample_app
            MYSQL_USER: app_user
            MYSQL_PASSWORD: AppUser123!
            TZ: 'Asia/Tokyo'
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./docker/mysql/70-app.cnf:/etc/mysql/mariadb.conf.d/70-app.cnf
            - ./volumes/mysql/mysql-data:/var/lib/mysql
            - ./volumes/mysql/log:/var/log/mysql
        networks:
            django-docker-network:
                ipv4_address: 192.168.50.101
        ports:
            - "3306:3306"
        # restart: always

    django-docker-nplus-sample-develop-app:
        image: django-docker-nplus-sample-develop-app:20220806
        container_name: django-docker-nplus-sample-develop-app
        hostname: django-docker-nplus-sample-develop-app
        # tty: true
        # restart: always
        # privileged: true  # systemctlを使う時に必要
        tty: true  # 常に起動しっぱなしにする 参考 : https://qiita.com/reflet/items/dd65f9ffef2a2fcfcf30
        depends_on:
            - django-docker-nplus-sample-develop-mariadb
        networks:
            django-docker-network:
                ipv4_address: 192.168.50.201
        volumes:
            - ./app:/usr/local/app
            - ./volumes/app/dump:/tmp/dump
        environment:
            DJANGO_SECRET_KEY: GT3MT5b9q2Vs2kMvtVFaLeiDNn7Fwyim
            DJANGO_SETTINGS_MODULE: config.settings.local
            DJANGO_ADMIN_URL: admin
            ALLOWED_HOSTS: "*"
            DB_HOST: django-docker-nplus-sample-develop-mariadb
            DB_USER: app_user
            DB_PASSWORD: AppUser123!
            DB_NAME: sample_app
        ports:
            - 8001:8001
        
    # django-docker-develop-lb-nginx:
    #     image: django-docker-nplus-sample-develop-lb-nginx:20220806
    #     container_name: django-nplus-sample-docker-develop-lb-nginx
    #     hostname: django-docker-nplus-sample-develop-lb-nginx
    #     # restart: always
    #     # privileged: true  # systemctlを使う時に必要
    #     tty: true  # 常に起動しっぱなしにする 参考 : https://qiita.com/reflet/items/dd65f9ffef2a2fcfcf30
    #     networks:
    #         django-docker-network:
    #             ipv4_address: 192.168.50.110
    #     ports:
    #         - 80:80
    #         - 443:443
