# Generated by Django 3.2.7 on 2021-09-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '地方マスタ',
                'verbose_name_plural': '地方マスタ',
                'db_table': 'master_district',
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='性別名')),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': '性別マスタ',
                'verbose_name_plural': '性別マスタ',
                'db_table': 'master_sex',
            },
        ),
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='都道府県名')),
                ('sequence', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.district')),
            ],
            options={
                'verbose_name': '都道府県マスタ',
                'verbose_name_plural': '都道府県マスタ',
                'db_table': 'master_prefecture',
            },
        ),
    ]
