# Generated by Django 3.2.7 on 2021-09-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='氏名')),
                ('name_kana', models.CharField(max_length=128, verbose_name='氏名（カタカナ）')),
                ('telephone', models.CharField(max_length=128, verbose_name='電話番号')),
                ('telephone_mobile', models.CharField(max_length=128, verbose_name='携帯電話')),
                ('mail_address', models.CharField(max_length=255, verbose_name='メールアドレス')),
                ('zip_code', models.CharField(max_length=32, verbose_name='郵便番号')),
                ('address1', models.CharField(max_length=255, verbose_name='住所1')),
                ('address2', models.CharField(max_length=255, verbose_name='住所1')),
                ('birthday', models.DateField(verbose_name='生年月日')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.prefecture')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.sex')),
            ],
            options={
                'verbose_name': '個人',
                'verbose_name_plural': '個人',
                'db_table': 'person',
            },
        ),
    ]
